//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioDevices
{
    using System;
    using System.Collections.Generic;
    
    public partial class CdDiscMan
    {
        public int SerialId { get; set; }
        public string Model { get; set; }
        public string Make { get; set; }
        public decimal PriceExBtw { get; set; }
        public System.DateTime CreationDate { get; set; }
        public decimal BtwPercentage { get; set; }
        public int MbSize { get; set; }
        public int DisplayWidth { get; set; }
        public int DisplayHeight { get; set; }
        public bool IsEjected { get; set; }
    
        public virtual AudioDevice AudioDevice { get; set; }
    }
}
